// GENERATED by desktop/make-copy-code.ts (the rebuild runs it) -- do not edit.
// A fingerprint of everything that could change what desktop/duckn-copy.ts writes.
export const COPY_SOURCE_CODE = "eb49edf390ed";
